@hostname = hackathon-backend-3688.onrender.com
@port = 80
@host = {{hostname}}:{{port}}


### Créer un utilisateur (suivi de l'envoi d'un email avec token)
POST http://{{host}}/api/auth/register
Content-Type: application/json

{
  "username": "wtf64d",
  "email": "hg64off+boiteaidee02@gmail.com",
  "password": "superMotDePasse",
  "passwordConfirm": "superMotDePasse"
}


### Vérifier l'email (à gérer côté front normalement)
GET http://{{host}}/api/auth/verify-email/:token
Content-Type: application/json


### Connexion utilisateur
POST http://{{host}}/api/auth/login
Content-Type: application/json

{
  "email": "hg64off+boiteaidee02@gmail.com",
  "password": "superMotDePasse"
}


### Mot de passe oublié (suivi de l'envoi d'un email avec token)
POST http://{{host}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "hg64off+boiteaidee01@gmail.com"
}


### Lien de confirmation avec token pour autoriser le reset (à gérer côté front)
GET http://{{host}}/api/auth/reset-password/:token
Content-Type: application/json


### Réinitialiser le mot de passe avec token
POST http://{{host}}/api/auth/reset-password/:token
Content-Type: application/json

{
  "password": "nouveauMotDePasse",
  "passwordConfirm": "nouveauMotDePasse"
}