

### Variables globales (remplace par tes vraies valeurs après chaque étape)
@baseUrl = http://localhost:3002/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJoZzY0b2ZmK2JvaXRlYWlkZWUwMUBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc1NDU2NTU1MCwiZXhwIjoxNzU0NjUxOTUwfQ.Xpn8bu186R0_lea3HwpBjUHTa1e0aK3Ygk2RYT5lqNw
@userId = 1  # À récupérer après register
@ideaId = 61
@commentId = 1  # À récupérer après création de commentaire

### Get Idees
GET {{baseUrl}}/ideas

### Récupérer toutes les idées (avec les options)
GET {{baseUrl}}/ideas?order=DESC&limit=2&offset=2&category_ids=3,6
Content-Type: application/json

### Récupérer toutes les idées (avec les options)
GET {{baseUrl}}/ideas?category_ids=3,6
Content-Type: application/json


### Connexion utilisateur
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "hg64off+boiteaidee01@gmail.com",
  "password": "superMotDePasse"
}

### 2.1 Créer une première idée
POST {{baseUrl}}/ideas
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Une application pour organiser des hackathons en ligne",
  "categories": ["Autres"]
}

### 4.2 Liker une idée
POST {{baseUrl}}/ideas/{{ideaId}}/likes
Content-Type: application/json
Authorization: Bearer {{token}}

### 4.4 Unliker l'idée
DELETE {{baseUrl}}/ideas/{{ideaId}}/likes
Authorization: Bearer {{token}}

### 5.1 Voir les commentaires d'une idée
GET {{baseUrl}}/ideas/{{ideaId}}/comments

###

### 5.2 Ajouter un commentaire
POST {{baseUrl}}/ideas/{{ideaId}}/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Excellente idée ! J'aimerais participer au développement."
}