INSERT INTO ideas (text, user_id) VALUES ('Créer une application de gestion de tâches', 2);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un service de livraison de repas locaux', 2);
INSERT INTO ideas (text, user_id) VALUES ('Développer un jeu mobile éducatif', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer une plateforme de covoiturage entre collègues', 6);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un blog sur les énergies renouvelables', 6);
INSERT INTO ideas (text, user_id) VALUES ('Mettre en place une newsletter sur les cryptomonnaies', 2);
INSERT INTO ideas (text, user_id) VALUES ('Concevoir une app de méditation pour enfants', 2);
INSERT INTO ideas (text, user_id) VALUES ('Développer un outil de prise de notes collaboratif', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer un réseau social pour passionnés de jardinage', 1);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un site de partage de recettes anti-gaspillage', 2);
INSERT INTO ideas (text, user_id) VALUES ('Construire une marketplace pour artisans locaux', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer un plugin de sécurité pour WordPress', 6);
INSERT INTO ideas (text, user_id) VALUES ('Développer une plateforme de micro-learning', 1);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un service d’abonnement à des plantes', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer une app de suivi de consommation d’énergie', 1);
INSERT INTO ideas (text, user_id) VALUES ('Mettre en place un simulateur de budget personnel', 1);
INSERT INTO ideas (text, user_id) VALUES ('Développer une appli de coaching sportif personnalisé', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer un site de mise en relation pour freelances', 2);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un comparateur de banques éthiques', 2);
INSERT INTO ideas (text, user_id) VALUES ('Créer une app de journal intime vocal', 6);
INSERT INTO ideas (text, user_id) VALUES ('Développer une plateforme d’échange de compétences', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer un service de dons alimentaires entre voisins', 1);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un site de bons plans écoresponsables', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer un gestionnaire de listes de lecture musicales', 2);
INSERT INTO ideas (text, user_id) VALUES ('Développer une appli de bons plans étudiants', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer un outil d’organisation de voyages en groupe', 2);
INSERT INTO ideas (text, user_id) VALUES ('Lancer une app de défis créatifs quotidiens', 2);
INSERT INTO ideas (text, user_id) VALUES ('Développer un calendrier de cycle de sommeil', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer une plateforme d’astuces de bricolage', 1);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un blog sur le minimalisme numérique', 2);
INSERT INTO ideas (text, user_id) VALUES ('Créer un chatbot d’assistance administrative', 1);
INSERT INTO ideas (text, user_id) VALUES ('Développer un outil de feedback anonyme pour employés', 6);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un site de mentorat intergénérationnel', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer une app de défis de bien-être en équipe', 2);
INSERT INTO ideas (text, user_id) VALUES ('Développer une plateforme de bénévolat local', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer un site de vente de vêtements upcyclés', 6);
INSERT INTO ideas (text, user_id) VALUES ('Lancer une appli d’apprentissage du code pour ados', 2);
INSERT INTO ideas (text, user_id) VALUES ('Créer un forum de discussion sur les sciences', 6);
INSERT INTO ideas (text, user_id) VALUES ('Développer un carnet de santé numérique familial', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer une base de données de films rares', 1);
INSERT INTO ideas (text, user_id) VALUES ('Lancer une app de suivi des objectifs mensuels', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer une app d’écriture collaborative de romans', 2);
INSERT INTO ideas (text, user_id) VALUES ('Développer un site de résumés de livres', 6);
INSERT INTO ideas (text, user_id) VALUES ('Créer un outil d’échange de services gratuits', 1);
INSERT INTO ideas (text, user_id) VALUES ('Lancer une appli de sport en plein air', 2);
INSERT INTO ideas (text, user_id) VALUES ('Créer une plateforme de projets open-source collaboratifs', 1);
INSERT INTO ideas (text, user_id) VALUES ('Développer un outil de planification de mariage', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer un simulateur d’entretien d’embauche', 2);
INSERT INTO ideas (text, user_id) VALUES ('Lancer un site de location de matériel de loisirs', 1);
INSERT INTO ideas (text, user_id) VALUES ('Créer une appli de défis zéro déchet', 1);